version: '3.7'
services:
    front:
        build: Angular
        ports:
            - "4200:4200"
        networks:
            - net


    node:
        build: Node
        ports:
            - "3000:3000"
        networks:
            - net
        restart: on-failure
        depends_on:
            - db

    db:
        image: mysql:5.7
        networks:
            - net
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root

    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        networks:
            - net

networks:
    net:
        driver: bridge
